name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        env:
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          LIQPAY_PUBLIC_KEY: ${{ secrets.LIQPAY_PUBLIC_KEY }}
          LIQPAY_PRIVATE_KEY: ${{ secrets.LIQPAY_PRIVATE_KEY }}
          LIQPAY_CALLBACK_URL: ${{ secrets. LIQPAY_CALLBACK_URL}}
          LIQPAY_IS_SANDBOX: ${{ secrets. LIQPAY_IS_SANDBOX}}
          TELEGRAM_BOT_TOKEN: ${{ secrets. TELEGRAM_BOT_TOKEN}}
          TELEGRAM_BOT_URL: ${{ secrets. TELEGRAM_BOT_URL}}
          TELEGRAM_BOT_NAME: ${{ secrets. TELEGRAM_BOT_NAME}}
          SUPER_ADMIN_EMAILS: ${{ secrets. SUPER_ADMIN_EMAILS}}

        run: mvn --batch-mode --update-snapshots verify
